### ISSUE TITLE
USER STORY: Site pagination

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#1]
As a  **Site User** I can **view a paginated list of posts** so that I **can select a post to view**.

### Acceptance Criteria :

-    Acceptance Criteria 1:a divided list of items for smaller pages based on a specified page size.
-    Acceptance Criteria 2: the “Previous” and “Next” buttons adjust the current page, ensuring it stays within the valid range

### Tasks:

- [ ] adjust the view of the page depending on the page size
- [ ] the view should be the same color scheme thrue out the project
- [ ] opens with buttons on each side and ajusted depending on the view
- [ ] test the functionality of the display

Iteration:#2
Points:#1
