### ISSUE TITLE
USER STORY:Account registration 

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#2]
As a **Site User** I can **register an account** so that I **can comment and like**.

### Acceptance Criteria:

-    Acceptance criteria 1: as a registered user i should be able to enter my details to login my account
-    Acceptance criteria 2: after entering my details and login in I should get a visual conformation that I am logged in
-    Acceptance criteria 3: if i provide wrong information,the site informs me of that and prevents the log in

### Tasks

- [ ] Develop a link to a login page
- [ ] Develop a login form for users to confirm their log in details
- [ ] Develop form validation to ensure the data is entered correctly
- [ ] Develop a method to validate the data entered matches a user account
- [ ] Develop a redirect so unlogged in users are redirected to the login page when trying to access pages that require the user to be logged in.

Iteration:https:#2
Points:#3
