### ISSUE TITLE
USER STORY:Comment on a post

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#3]
As a **Site User**, I can ****leave comments on a post** so I can be **involved in the conversation**.

### Acceptance criteria:

-    Acceptance criteria 1: the option should appear on a given comment to add
-    Acceptance criteria 2:  After confirmation the view should be adjusted and the username displayed

### Tasks:

- [ ] create a new field for the comment below the original
- [ ] possibility edit or remove a comment
- [ ] adjust the size of the field on the screen used
- [ ] test functionality

Iteration:#2
Points:#2
