### ISSUE TITLE
USER STORY: Reset your password 

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#4]
As a **Site Admin** I can **reset the password** so that the **user can get access to his account**.

### Acceptance criteria:

-    Acceptance criteria 1:possibility to reset the password
-    Acceptance criteria 2:option to reset the password provided under the submit button
-    Acceptance criteria 3:alert if the password is not using the listed characters

### Tasks:

- [ ] adding the part with allowed characters for the password
- [ ] alert message for the incorrect input
- [ ] update the new password
- [ ] test the functionality

Itiration:#2
Points:#5
