### ISSUE TITLE
USER STORY: View likes 

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#5]
As a **Site User / Admin** I can **view the number of likes on each post** so that I **can see which is the most popular or viral.**

### Acceptance Criteria:

-    Acceptance criteria 1: i should be able to view the popular post
-    Acceptance criteria 2: the option to like the post should be next to submit button
-    Acceptance criteria 3:the number of likes should be displayed
-    Acceptance critearia 4: the view or the post popularty should be updated

### Tasks:

- [ ] update the view: the post should have a like button next to submit
- [ ] create a new field that track the number of like on the post
- [ ] the number of the likes on the post should display with everytime someone comments
- [ ] test the functionality

Iteration:#2
Points:#1
