### ISSUE TITLE
USER STORY: Create review drafts 

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#6]
As a **Site Admin** I can **create draft of the reviews** so **that I can finish writing the content later and leave my personal review**.

### Acceptance Criteria:

-    Acceptance Criteria 1:under the description of the book a tap for reviews
-    Acceptance Criteria 2: i can enter my user name , tittle and add the description or review
-    Acceptance Criteria 3: the window should show the winnig score
-    Acceptance Criteria 4: the closing or better said the save button
-    Acceptance Criteria 5: is displayed on the site

### Tasks:

- [ ] fit the design(HTML and CSS) for the the view on desktop and phone
- [ ] under the description of the book a tap for reviews
- [ ] opens window for reviews
- [ ] test the functionality of the display

Iteration:#2
Points:#1
