### ISSUE TITLE
USER STORY: View comments

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#7]
As a **Site User / Admin** I can **view comments on an individual post** so that I **can read the conversation.**

### Acceptance Criteria :

-    Acceptance Criteria 1:the option to alternate should be only admin site
-    Acceptance Criteria 2: the converstation should be displayed on main page of the book description
-    Acceptance Criteria 3: after submiting and viewing the comments the page should adjust , remove the comment or keep it

### Tasks:

- [ ] adjust the view depending on the screen size
- [ ] adjust the comment section if i comment is deleted
- [ ] update the unit test script
- [ ] test the functionality

Iteration:https:#2
Points:https:#2
