### ISSUE TITLE
USER STORY: Poll of 5 most popular overall

### ISSUE THREAD

**Issue by AnaD30** [AnaD30/bookblog#8]
As a **Site Admin** I can **create draft poll of the 5 best books** so that I **can highlight the best books that stand out.**

### Acceptance Criteria :

-    Acceptance Criteria 1:develop alink at the main page of the poll
-    Acceptance Criteria 2: the display of the poll should be in a seperate window
-    Acceptance Criteria 3: the window should show the winnig score
-    Acceptance Criteria 4: update after a month
-    Acceptance Criteria 5: develop a close button of the window

### Tasks:

- [ ] fit the design(HTML and CSS) for the the view on desktop and phone
- [ ] develop a link link to the poll on the main site
- [ ] create a new field where the name of the top5 books is displayed
- [ ] the pool should update after a month
- [ ] test the functionality of the display

Iteration:https:#2
Points:https:#3
